### ISSUE TITLE
Failing to build v0.21.0

### ISSUE THREAD

**Issue by MattouFP** [paulcbetts/grunt-build-atom-shell#16]
When trying to build against v0.21.0, boostrap.py fails when it comes to installing apm modules.  
This issue has already been reported in:

atom/apm#281
atom/node-nslog#4
atom/atom-shell#1070

APM versions:

```
C:\app>"C:\app\build\atom-shell\node_modules\atom-package-
manager\bin\apm.cmd" --version
apm  0.126.0
npm  2.1.18
node 0.10.35
python 2.7.8
git 1.9.5.msysgit.0
visual studio 2013
```

Command output:

```
C:\app\build\atom-shell\node_modules\atom-package-manager\bin\apm.cmd
 install
Installing modules failed
> runas@1.1.0 install C:\app\build\atom-shell\spec\node_modules\runas

> node-gyp rebuild


C:\app\build\atom-shell\spec\node_modules\runas>node "C:\app\
build\atom-shell\node_modules\atom-package-manager\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
G?n?ration des projets individuellement dans cette solution. Pour activer la g?n
?ration en parall?le, ajoutez le commutateur "/m".
  main.cc
  runas_win.cc
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(623): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::Str
ing' (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\runa
s\build\runas.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(623): error C2065: 'ExternalAsciiStringResource' : undeclared identifier (..\s
rc\main.cc) [C:\app\build\atom-shell\spec\node_modules\runas\build\ru
nas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(623): error C2065: 'resource' : undeclared identifier (..\src\main.cc) [C:\app
\build\atom-shell\spec\node_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(623): error C2448: 'NanNew' : function-style initializer appears to be a funct
ion definition (..\src\main.cc) [C:\app\build\atom-shell\spec\node_mo
dules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(672): warning C4244: 'return' : conversion from 'int64_t' to 'int', possible l
oss of data (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modul
es\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1993): error C2039: 'IsExternalAscii' : is not a member of 'v8::String' (..\sr
c\main.cc) [C:\app\build\atom-shell\spec\node_modules\runas\build\run
as.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1994): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::St
ring' (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\run
as\build\runas.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1994): error C4430: missing type specifier - int assumed. Note: C++ does not s
upport default-int (..\src\main.cc) [C:\app\build\atom-shell\spec\nod
e_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1994): error C2143: syntax error : missing ';' before '*' (..\src\main.cc) [C:
\app\build\atom-shell\spec\node_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1994): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\app
\build\atom-shell\spec\node_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1995): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\app
\build\atom-shell\spec\node_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1995): error C2039: 'GetExternalAsciiStringResource' : is not a member of 'v8:
:String' (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\
runas\build\runas.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1996): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\app\
build\atom-shell\spec\node_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1996): error C2227: left of '->data' must point to class/struct/union/generic
type (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\runa
s\build\runas.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1997): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\app
\build\atom-shell\spec\node_modules\runas\build\runas.vcxproj]
C:\app\build\atom-shell\spec\node_modules\runas\node_modules\nan\nan.
h(1997): error C2227: left of '->length' must point to class/struct/union/generi
c type (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\ru
nas\build\runas.vcxproj]
          type is 'unknown-type'

> pathwatcher@2.6.1 install C:\app\build\atom-shell\spec\node_modules
\pathwatcher
> node-gyp rebuild


C:\app\build\atom-shell\spec\node_modules\pathwatcher>node "C:\app
\build\atom-shell\node_modules\atom-package-manager\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
G?n?ration des projets individuellement dans cette solution. Pour activer la g?n
?ration en parall?le, ajoutez le commutateur "/m".
  main.cc
  common.cc
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v
8::String' (..\src\main.cc) [C:\app\build\atom-shell\spec\node_module
s\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'ExternalAsciiStringResource' : undeclared identifier
 (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatc
her\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'resource' : undeclared identifier (..\src\main.cc) [
C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatch
er.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2448: 'NanNew' : function-style initializer appears to be a
 function definition (..\src\main.cc) [C:\app\build\atom-shell\spec\n
ode_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v
8::String' (..\src\common.cc) [C:\app\build\atom-shell\spec\node_modu
les\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'ExternalAsciiStringResource' : undeclared identifier
 (..\src\common.cc) [C:\app\build\atom-shell\spec\node_modules\pathwa
tcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'resource' : undeclared identifier (..\src\common.cc)
 [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwat
cher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1993): error C2039: 'IsExternalAscii' : is not a member of 'v8::String'
(..\src\main.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatch
er\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2448: 'NanNew' : function-style initializer appears to be a
 function definition (..\src\common.cc) [C:\app\build\atom-shell\spec
\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2039: 'ExternalAsciiStringResource' : is not a member of '
v8::String' (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modul
es\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\main.cc) [C:\app\build\atom-shell\sp
ec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2143: syntax error : missing ';' before '*' (..\src\main.c
c) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathw
atcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\
app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher.v
cxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\
app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher.v
cxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2039: 'GetExternalAsciiStringResource' : is not a member o
f 'v8::String' (..\src\main.cc) [C:\app\build\atom-shell\spec\node_mo
dules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\
app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher.v
cxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2227: left of '->data' must point to class/struct/union/ge
neric type (..\src\main.cc) [C:\app\build\atom-shell\spec\node_module
s\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\
app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher.v
cxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2227: left of '->length' must point to class/struct/union/
generic type (..\src\main.cc) [C:\app\build\atom-shell\spec\node_modu
les\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1993): error C2039: 'IsExternalAscii' : is not a member of 'v8::String'
(..\src\common.cc) [C:\app\build\atom-shell\spec\node_modules\pathwat
cher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2039: 'ExternalAsciiStringResource' : is not a member of '
v8::String' (..\src\common.cc) [C:\app\build\atom-shell\spec\node_mod
ules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\common.cc) [C:\app\build\atom-shell\
spec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2143: syntax error : missing ';' before '*' (..\src\common
.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pat
hwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2065: 'ext' : undeclared identifier (..\src\common.cc) [C:
\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher
.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2065: 'ext' : undeclared identifier (..\src\common.cc) [C:
\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher
.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2039: 'GetExternalAsciiStringResource' : is not a member o
f 'v8::String' (..\src\common.cc) [C:\app\build\atom-shell\spec\node_
modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2065: 'ext' : undeclared identifier (..\src\common.cc) [C:
\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher
.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2227: left of '->data' must point to class/struct/union/ge
neric type (..\src\common.cc) [C:\app\build\atom-shell\spec\node_modu
les\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2065: 'ext' : undeclared identifier (..\src\common.cc) [C:
\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwatcher
.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2227: left of '->length' must point to class/struct/union/
generic type (..\src\common.cc) [C:\app\build\atom-shell\spec\node_mo
dules\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
  handle_map.cc
  pathwatcher_win.cc
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v
8::String' (..\src\handle_map.cc) [C:\app\build\atom-shell\spec\node_
modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'ExternalAsciiStringResource' : undeclared identifier
 (..\src\handle_map.cc) [C:\app\build\atom-shell\spec\node_modules\pa
thwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'resource' : undeclared identifier (..\src\handle_map
.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pat
hwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2448: 'NanNew' : function-style initializer appears to be a
 function definition (..\src\handle_map.cc) [C:\app\build\atom-shell\
spec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1993): error C2039: 'IsExternalAscii' : is not a member of 'v8::String'
(..\src\handle_map.cc) [C:\app\build\atom-shell\spec\node_modules\pat
hwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2039: 'ExternalAsciiStringResource' : is not a member of '
v8::String' (..\src\handle_map.cc) [C:\app\build\atom-shell\spec\node
_modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\handle_map.cc) [C:\app\build\atom-sh
ell\spec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2143: syntax error : missing ';' before '*' (..\src\handle
_map.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build
\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2065: 'ext' : undeclared identifier (..\src\handle_map.cc)
 [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwat
cher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2065: 'ext' : undeclared identifier (..\src\handle_map.cc)
 [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwat
cher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2039: 'GetExternalAsciiStringResource' : is not a member o
f 'v8::String' (..\src\handle_map.cc) [C:\app\build\atom-shell\spec\n
ode_modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2065: 'ext' : undeclared identifier (..\src\handle_map.cc)
 [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwat
cher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2227: left of '->data' must point to class/struct/union/ge
neric type (..\src\handle_map.cc) [C:\app\build\atom-shell\spec\node_
modules\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2065: 'ext' : undeclared identifier (..\src\handle_map.cc)
 [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pathwat
cher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2227: left of '->length' must point to class/struct/union/
generic type (..\src\handle_map.cc) [C:\app\build\atom-shell\spec\nod
e_modules\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v
8::String' (..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\spec\
node_modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'ExternalAsciiStringResource' : undeclared identifier
 (..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\spec\node_modul
es\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2065: 'resource' : undeclared identifier (..\src\pathwatche
r_win.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\buil
d\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(623): error C2448: 'NanNew' : function-style initializer appears to be a
 function definition (..\src\pathwatcher_win.cc) [C:\app\build\atom-s
hell\spec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1993): error C2039: 'IsExternalAscii' : is not a member of 'v8::String'
(..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\spec\node_module
s\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2039: 'ExternalAsciiStringResource' : is not a member of '
v8::String' (..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\spec
\node_modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\pathwatcher_win.cc) [C:\app\build\at
om-shell\spec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2143: syntax error : missing ';' before '*' (..\src\pathwa
tcher_win.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\
build\pathwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1994): error C2065: 'ext' : undeclared identifier (..\src\pathwatcher_wi
n.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pa
thwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2065: 'ext' : undeclared identifier (..\src\pathwatcher_wi
n.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pa
thwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1995): error C2039: 'GetExternalAsciiStringResource' : is not a member o
f 'v8::String' (..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\s
pec\node_modules\pathwatcher\build\pathwatcher.vcxproj]
          D:\Utilisateurs\Matteo\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\includ
e\v8.h(1809) : see declaration of 'v8::String'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2065: 'ext' : undeclared identifier (..\src\pathwatcher_wi
n.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pa
thwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1996): error C2227: left of '->data' must point to class/struct/union/ge
neric type (..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\spec\
node_modules\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2065: 'ext' : undeclared identifier (..\src\pathwatcher_wi
n.cc) [C:\app\build\atom-shell\spec\node_modules\pathwatcher\build\pa
thwatcher.vcxproj]
C:\app\build\atom-shell\spec\node_modules\pathwatcher\node_modules\na
n\nan.h(1997): error C2227: left of '->length' must point to class/struct/union/
generic type (..\src\pathwatcher_win.cc) [C:\app\build\atom-shell\spe
c\node_modules\pathwatcher\build\pathwatcher.vcxproj]
          type is 'unknown-type'

npm WARN package.json atom-shell-specs@0.1.0 No description
npm WARN package.json atom-shell-specs@0.1.0 No repository field.
npm WARN package.json atom-shell-specs@0.1.0 No README data
gypgypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\app\\build\\atom-shell\\node_modules\\atom-packa
ge-manager\\bin\\\\node.exe" "C:\app\\build\\atom-shell\\node_modu
les\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig"
"C:\app\\build\\atom-shell\\node_modules\\atom-package-manager\\.a
pmrc" "--userconfig" "D:\\Utilisateurs\\Matteo\\.atom\\.apmrc" "install" "--targ
et=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "C:\app\build\atom-shell\script\lib\util.py", line 148, in exe
cute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\app\\build\\atom-shel
l\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-z
ero exit status 1
```

**Comment by paulcbetts** [comment]
I *just* fixed this up last night, can you pull and try again?

**Comment by MattouFP** [comment]
Do you mean in version 1.1.5?

**Comment by paulcbetts** [comment]
@MattouFP I thought this was in atom-shell-starter, sorry. It should be fixed in 1.1.5. These errors look like a mismatched node version setting tbh

**Comment by MattouFP** [comment]
Fixed by the latest commit in atom-shell and using nodeVersion 0.21.0. Thanks!

**Comment by MattouFP** [comment]
Note: I had to use nodeVersion 0.20.0, not 0.21.0, sorry for the typo.

**Comment by paulcbetts** [comment]
Uh, what? You should definitely use 0.21.0 against the commit currently pinned in master

**Comment by MattouFP** [comment]
My mistake. It works both with 0.20.0 and 0.21.0, just forgot to bump the version.

**Comment by paulcbetts** [comment]
@MattouFP Cool app btw!

**Comment by MattouFP** [comment]
Thanks!
