### ISSUE TITLE
Error with subprocess.CalledProcessError: Command

### ISSUE THREAD

**Issue by jonniespratley** [paulcbetts/grunt-build-atom-shell#32]
Any ideas on why this is happening?

Here is the input:

```
    'build-atom-shell': {
      tag: 'v0.19.5',
      nodeVersion: '0.18.0',
      config: 'Debug',
      buildDir: './temp',
      projectName: 'predixgo',
      productName: 'PredixGo'
    },
```

Here is the output:

```
Running "build-atom-shell" task
Verifying properties build-atom-shell.buildDir, build-atom-shell.tag, build-atom-shell.projectName, build-atom-shell.productName exist in config...OK
>> Running: git remote set-url origin https://github.com/atom/atom-shell
>> Running: git fetch origin
>> Running: git reset --hard HEAD
>> Running: git checkout v0.19.5
>> Rigging atom.gyp to have correct name
Reading temp/atom-shell/atom.gyp...OK
Writing temp/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 119, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 25, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 73, in update_atom_modules
>>     execute([apm, 'install'])
>>   File "/Users/predixgo/GithubEnterprise/pg-atomshell-container/temp/atom-shell/script/lib/util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['/Users/predixgo/GithubEnterprise/pg-atomshell-container/temp/atom-shell/node_modules/.bin/apm', 'install']' returned non-zero exit status 133
>> Rigging atom.gyp to have correct name
Reading temp/atom-shell/atom.gyp...OK
Writing temp/atom-shell/atom.gyp...OK
>> Running: python script/bootstrap.py -v
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 119, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 25, in main
>>     update_atom_modules('spec')
>>   File "script/bootstrap.py", line 73, in update_atom_modules
>>     execute([apm, 'install'])
>>   File "/Users/predixgo/GithubEnterprise/pg-atomshell-container/temp/atom-shell/script/lib/util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['/Users/predixgo/GithubEnterprise/pg-atomshell-container/temp/atom-shell/node_modules/.bin/apm', 'install']' returned non-zero exit status 133
Warning: null Use --force to continue.

Aborted due to warnings.
```

**Comment by paulcbetts** [comment]
This usually happens when your version of node.js is not 0.10.x
